export enum BlogContract {
  name = 'Blog',
  owner = 'owner',
  getAllBlogs = 'getAllBlogs',
  getDeletedBlogs = 'getDeletedBlogs',
  addBlog = 'addBlog',
  editBlog = 'editBlog',
  deleteBlog = 'deleteBlog',
  publish = 'publish',
  unpublish = 'unpublish',
  getUserInfo = 'getUserInfo',
  saveUserInfo = 'saveUserInfo',
  follow = 'follow',
  unfollow = 'unfollow',
  isFollowing = 'isFollowing',
  getNumFollowers = 'getNumFollowers',
  likeBlogPost = 'likeBlogPost',
  unlikeBlogPost = 'unlikeBlogPost',
  getLikesForBlogPost = 'getLikesForBlogPost',
  getCommentsForBlogPost = 'getCommentsForBlogPost',
  addCommentToBlogPost = 'addCommentToBlogPost',
  editCommentForBlogPost = 'editCommentForBlogPost',
  deleteCommentForBlogPost = 'deleteCommentForBlogPost',
  getTheme = 'getTheme',
  setTheme = 'setTheme',
}

export enum RoutesEnum {
  home = '/',
  blog = '/blog',
  deleted_blog = '/deleted_blog',
  admin = '/admin',
  create = '/create',
  edit = '/edit',
  profile = '/profile',
  edit_profile = '/edit_profile',
  customize = '/customize',
}

export const backgroundColors = ['zinc', 'slate', 'gray', 'neutral'];

export const primaryColors = [
    'red',
    'orange',
    'amber',
    'yellow',
    'lime',
    'green',
    'emerald',
    'teal',
    'cyan',
    'sky',
    'blue',
    'indigo',
    'violet',
    'purple',
    'fuchsia',
    'pink',
    'rose',
    'slate'
];
